import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#494643',
        'on-secondary-container': '#3c5980',
        'background': '#f9f9fe',
        'on-background': '#1a1c1f',
        'on-surface-variant': '#554337',
        'on-secondary-fixed': '#001c39',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#1d1b19',
        'outline': '#887365',
        'secondary-fixed': '#d3e3ff',
        'primary-fixed': '#ffdcc5',
        'error-container': '#ffdad6',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#301400',
        'surface-container': '#ededf3',
        'surface-container-highest': '#e2e2e7',
        'on-tertiary-container': '#3d3b38',
        'outline-variant': '#dbc2b2',
        'on-primary': '#ffffff',
        'error': '#ba1a1a',
        'tertiary': '#615e5a',
        'secondary-container': '#b3d1fe',
        'surface-container-low': '#f3f3f8',
        'inverse-on-surface': '#f0f0f5',
        'surface': '#f9f9fe',
        'on-surface': '#1a1c1f',
        'secondary': '#426087',
        'surface-container-high': '#e8e8ed',
        'primary-container': '#f28c38',
        'on-primary-fixed-variant': '#713700',
        'tertiary-fixed-dim': '#cbc6c1',
        'primary': '#944a00',
        'surface-tint': '#944a00',
        'tertiary-fixed': '#e7e1dd',
        'inverse-primary': '#ffb783',
        'secondary-fixed-dim': '#abc8f5',
        'surface-variant': '#e2e2e7',
        'tertiary-container': '#a9a5a1',
        'on-secondary': '#ffffff',
        'surface-dim': '#d9dadf',
        'surface-bright': '#f9f9fe',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#2e3034',
        'primary-fixed-dim': '#ffb783',
        'on-secondary-fixed-variant': '#2a486e',
        'on-primary-container': '#602e00',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      fontFamily: {
        headline: ['var(--font-manrope)'],
        body: ['var(--font-inter)'],
        label: ['var(--font-inter)'],
      },
    },
  },
  plugins: [],
};

export default config;
